### ISSUE TITLE
Testing Your First Application lesson is outdated

### ISSUE THREAD

**Issue by juanparadox** [cypress-io/cypress-realworld-testing#140]
I was going through the Testing Your First Application lesson and noticed that the [project](https://github.com/cypress-io/cypress-realworld-testing-todomvc) that the [documentation](https://learn.cypress.io/testing-your-first-application/installing-cypress-and-writing-our-first-test) suggests the user download does not match the instructions.

For example:

- The documentation instructs the user to install Cypress, but Cypress is already installed. 
- The documentation instructs the user to add a script to more easily run cypress, but that script already exists.
- The documentation instructs the user to run tests at `cypress/integration/examples`, but these tests do not exist.
- Screenshots do not match what the user sees when they run Cypress.

These are just a handful of examples. I am wondering if maybe there is already a ticket to address this or if there is another project that is barebones so that the user can incrementally add/ follow the documentation without it already being done for them. I also believe I might be overlooking a very obvious step in the documentation so if all of this isn't an issue, then please disregard.

**Comment by robertguss** [comment]
@juanparadox the testing your first app content is currently being re-written to work with Cypress 10. All of these issues you brought up will be addressed in the new content. Thank you so much for bringing this to our attention.
