### ISSUE TITLE
Advanced concepts image difficult to see

### ISSUE THREAD

**Issue by conversaShawn** [cypress-io/cypress-realworld-testing#151]
It'd be nice to either have an easier-to-read visual or better alt text.

![Screen Shot 2022-07-20 at 12 43 38 PM](https://user-images.githubusercontent.com/48733734/180254078-1cd73e45-5d81-4bf4-be1d-29c051802cdb.png)

**Comment by robertguss** [comment]
@conversaShawn thank you for pointing this out. I did a quick fix and simply added a white background to the image for the time being. I will try and find a better image though for a more permanent solution.
