### ISSUE TITLE
Within some screenshots, "https://localhost:3000" is used instead of "http://localhost:3000"

### ISSUE THREAD

**Issue by christoefle** [cypress-io/cypress-realworld-testing#174]
see installing-cypress-and-writing-your-first-test.mdx

and e,g, screenshot referenced as 
/images/testing-your-first-application/installing-cypress-and-writing-your-first-test/Screen_Shot_2022-06-28_at_9.21.56_AM.png

-> the screenshot shows the test pointing to https://localhost:3000
-> it should point to http://localhost:3000

**Comment by robertguss** [comment]
@christoefle thanks for pointing this out, however, I am not that concerned with this.
