### ISSUE TITLE
Failed to load SWC binary for darwin/arm64

### ISSUE THREAD

**Issue by o-t-w** [cypress-io/cypress-realworld-testing#236]
When running `npm run dev` in the start branch I had the following error 
```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
warn  - SWC minify release candidate enabled. https://nextjs.org/docs/messages/swc-minify-enabled
info  - Attempted to load @next/swc-darwin-arm64, but it was not installed
error - Failed to load SWC binary for darwin/arm64, see more info here: https://nextjs.org/docs/messages/failed-loading-swc
```

**Comment by NishantGautam023** [comment]
> When running `npm run dev` in the start branch I had the following error
> 
> ```
> ready - started server on 0.0.0.0:3000, url: http://localhost:3000
> warn  - SWC minify release candidate enabled. https://nextjs.org/docs/messages/swc-minify-enabled
> info  - Attempted to load @next/swc-darwin-arm64, but it was not installed
> error - Failed to load SWC binary for darwin/arm64, see more info here: https://nextjs.org/docs/messages/failed-loading-swc
> ```

I had the same error, you can try `npm install @next/swc-linux-x64-gnu`  or make a .babelrc file and add `
{
	  "presets": ["next/babel"]
}`

**Comment by augusticor** [comment]
I had the same issue in Windows, solved it using this [answer ](https://stackoverflow.com/questions/69816589/next-failed-to-load-swc-binary/70360521#70360521) from stackoverflow. It says:

```
Delete the package-lock.json file and the node_modules directory in your project and then run npm install on your terminal.

**Comment by NishantGautam023** [comment]
Yes the one worked for me  too!

**Comment by MikeMcC399** [comment]
Another workaround, which does not involve deleting files, is to execute:

```bash
npm install --no-package-lock
npm run dev
```

which shows

```text
$ npm run dev

> dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
warn  - Found lockfile missing swc dependencies, patching...
event - compiled client and server successfully in 1597 ms (179 modules)
warn  - Lockfile was successfully patched, please run "npm install" to ensure @next/swc dependencies are downloaded
```

then kill the server and execute

```bash
npm install
npm run dev
```

which results in a working server:

```text
$ npm run dev

> dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
warn  - SWC minify release candidate enabled. https://nextjs.org/docs/messages/swc-minify-enabled
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
event - compiled client and server successfully in 2.5s (129 modules)
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
```

The problem should however be fixed in the source of the training materials.

**Comment by MikeMcC399** [comment]
This issue is being addressed by:

- PR https://github.com/cypress-io/cypress-realworld-testing-course-app/pull/22 or
- PR https://github.com/cypress-io/cypress-realworld-testing-course-app/pull/23
