### ISSUE TITLE
start or final branch?

### ISSUE THREAD

**Issue by Onnaien** [cypress-io/cypress-realworld-testing#250]
The instructions from https://learn.cypress.io/testing-your-first-application/app-install-and-overview#cloning-with-git suggests cloning the start branch:
git clone --branch start git@github.com:cypress-io/cypress-realworld-testing-course-app.git

But on the screenshots from https://learn.cypress.io/testing-your-first-application/app-install-and-overview#vscode and down, the final branch is shown:
![image](https://user-images.githubusercontent.com/59879014/215839464-ad566f42-07ad-42a0-8a0a-33e92d1f48b4.png)

What is the correct branch to clone?

**Comment by elylucas** [comment]
Sorry about the late reply here, but the correct branch is the start branch. The final branch contains all the completed tests at the end of the course.
