### ISSUE TITLE
package.json and package-lock.json mismatch in start branch

### ISSUE THREAD

**Issue by Onnaien** [cypress-io/cypress-realworld-testing#251]
I am taught that it is a good idea to use `npm ci` to install the npm packages after cloning/pulling a repo to make sure to install exactly the packages that was used in development and testing. And those packages and versions are listed in the packages-lock.json file.

When I clone the start branch of the repo and run `npm ci`, I get this as a result:
![image](https://user-images.githubusercontent.com/59879014/215844783-07d2dc54-c46a-4372-840d-195b3f043414.png)

I think issue #236 comes from the same problem.

If I clone the repo and remove package-lock.json before I do `npm install`, the application starts up fine when running `npm run dev`.

I am also taught that when you get package and package-lock inconsistency, then delete the node_modules folder and package-lock file, and then run `npm install` to create a new package-lock file that is in sync with the package file.
That would be my recommended resolution.

And also to check in this updated package-lock file and update the documentation to suggest using `npm ci` instead of `npm install` instead to make sure the user installs "tested" packages.

Question:
Is there a reason that both start and final branches has failed commit checks since June 23 last year??:
![image](https://user-images.githubusercontent.com/59879014/215848411-51b1d138-354b-4e0c-9720-7d0b4d48b450.png)

**Comment by elylucas** [comment]
The dependencies for the learn app were recently updated and this issue should be fixed now. Let us know if it still pops up.
