### ISSUE TITLE
npm install lodash --save

### ISSUE THREAD

**Issue by lemitchv** [cypress-io/cypress-realworld-testing#253]
### Reproduction

1. follow the installation instruction
2. run `npm run dev`

### Observed result
the follwing error occurs:
`ready - started server on 0.0.0.0:3000, url: http://localhost:3000
event - compiled client and server successfully in 3.8s (179 modules)
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 238 ms (180 modules)
wait  - compiling / (client and server)...
error - ./machines/progressMachine.ts:3:0`
`Module not found: Can't resolve 'lodash/fp'`

### Fix
To fix it, i ran
`npm install lodash --save`

**Comment by elylucas** [comment]
Didn't run into this issue myself, but the dependencies get updated periodically. Going to close this one, but if you run into it again ping me here.
