### ISSUE TITLE
Outdated Node.js LTS screenshot showing v16.15.0 (end-of-life)

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-realworld-testing#290]
The instructions concerning the required version of Node.js in [Testing Your First Application > App Install and Overview](https://learn.cypress.io/testing-your-first-application/app-install-and-overview) are inconsistent.

Under "Installing the application" it says:

>You want to make sure that you download the “LTS” version of Node and not the “Current” version.
>
>This repo will be updated regularly to support the latest LTS versions only.

The [Node.js release schedule](https://github.com/nodejs/release#release-schedule) shows that Node.js `18.x` was the LTS (Long Term Support) version from Oct 25, 2022 to Oct 24, 2023 when Node.js `20.x` replaced it as designated LTS version.

The screenshot https://learn.cypress.io/images/testing-your-first-application/app-install-and-overview/Screen_Shot_2022-06-28_at_8.16.50_AM.png however shows an installed Node.js `v16.15.0` version. Node.js `16.x` ceased to be the LTS version on Oct 25, 2022. Cypress no longer supports Node.js `16` which entered end-of-life on Sep 11, 2023.

## Suggestion

Either remove the Node.js screenshot or replace it with one showing the current LTS version (~~`18.x.x`~~ `20.x.x`) - see https://nodejs.org/ for exact up-to-date version number of Node.js LTS.

**Comment by scottrassbach-utk** [comment]
Is anyone working on this example app anymore? I tried to install it on a Windows machine using VS code and updating all the old packages under node 20 LTS. It seems as though there is so much broken that it cannot be updated as is.

I am not a JavaScript expert, I'm just a senior Dev trying to set this up as an example for a junior QA person. I will be talking with our most experienced JavaScript person to see if they can get it running. Nonetheless, just wondering if this is going to be updated?

**Comment by MikeMcC399** [comment]
@scottrassbach-utk 

- This repo is not currently getting any attention from the Cypress.io team. I would recommend not trying to update dependencies, just run as-is. See also https://github.com/cypress-io/cypress-realworld-testing/issues/330

- There are more up-to-date training course available elsewhere.

**Comment by MikeMcC399** [comment]
@scottrassbach-utk 

PS If you are not already aware, there is an active technical community on Discord

[![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord) (click on button)

which might be useful to you.

**Comment by MikeMcC399** [comment]
Closed due to no feedback.
