### ISSUE TITLE
Cypress Course(Learn section) documentation typo

### ISSUE THREAD

**Issue by ArkaPrabhaChowdhury** [cypress-io/cypress-realworld-testing#296]
### Subject

Learn section typo

### Description

![image](https://user-images.githubusercontent.com/92904175/234204843-0ec206f1-eeec-4c6c-9e9e-790b35652e03.png)

"We can tell Cypress to only run a specific test **but** using it.only() like so" -> The "but" should be changed to "by"

**Comment by MikeMcC399** [comment]
The typo is in https://github.com/cypress-io/cypress-realworld-testing/blob/305f78e6caae81e6ca7ae6ac2196f3a35a5dd81e/content/courses/testing-your-first-application/installing-cypress-and-writing-your-first-test.mdx?plain=1#L392

**Comment by ArkaPrabhaChowdhury** [comment]
> The typo is in https://github.com/cypress-io/cypress-realworld-testing/blob/305f78e6caae81e6ca7ae6ac2196f3a35a5dd81e/content/courses/testing-your-first-application/installing-cypress-and-writing-your-first-test.mdx?plain=1#L392

Yes! Thank you! Should I make the changes?

**Comment by MikeMcC399** [comment]
@ArkaPrabhaChowdhury 
> Yes! Thank you! Should I make the changes?

That would make sense, yes. (I don't speak for the owner / maintainer though. I am just a community contributor.)
